CREATE DATABASE SchoolDB;
USE SchoolDB;

CREATE TABLE Students (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    FullName NVARCHAR(100) NOT NULL,
    Age INT CHECK (Age BETWEEN 6 AND 20),
    Email NVARCHAR(255) UNIQUE,
    Score INT DEFAULT 0 CHECK (Score BETWEEN 0 AND 100)
);

ALTER TABLE Students
ADD CreatedAt DATETIME DEFAULT GETDATE();

ALTER TABLE Students
ADD CONSTRAINT CK_Students_Score_DivisibleBy5
CHECK (Score % 5 = 0);

CREATE TABLE TopStudents (
    Id INT PRIMARY KEY,
    FullName NVARCHAR(100),
    Score INT
);

